//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public class VotingTable implements java.lang.Cloneable,
                                    java.io.Serializable
{
    public String location;

    public String city;

    public VotingTable()
    {
        this.location = "";
        this.city = "";
    }

    public VotingTable(String location, String city)
    {
        this.location = location;
        this.city = city;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        VotingTable r = null;
        if(rhs instanceof VotingTable)
        {
            r = (VotingTable)rhs;
        }

        if(r != null)
        {
            if(this.location != r.location)
            {
                if(this.location == null || r.location == null || !this.location.equals(r.location))
                {
                    return false;
                }
            }
            if(this.city != r.city)
            {
                if(this.city == null || r.city == null || !this.city.equals(r.city))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::VotingSystem::VotingTable");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, location);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, city);
        return h_;
    }

    public VotingTable clone()
    {
        VotingTable c = null;
        try
        {
            c = (VotingTable)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.location);
        ostr.writeString(this.city);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.location = istr.readString();
        this.city = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, VotingTable v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public VotingTable ice_read(com.zeroc.Ice.InputStream istr)
    {
        VotingTable v = new VotingTable();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<VotingTable> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, VotingTable v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<VotingTable> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(VotingTable.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final VotingTable _nullMarshalValue = new VotingTable();

    /** @hidden */
    public static final long serialVersionUID = -796694902L;
}
